# Generated by Django 3.0.7 on 2021-06-29 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='optional_text',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='rating',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='5', max_length=6),
        ),
    ]
