# Generated by Django 3.0.7 on 2021-06-29 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20210629_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='rating',
            field=models.CharField(choices=[('1', '1 star'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='5', max_length=6),
        ),
    ]
