# Generated by Django 3.0.7 on 2021-06-29 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_auto_20210629_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='rating',
            field=models.CharField(choices=[('1 star', '1'), ('2 star', '2'), ('3 star', '3'), ('4 star', '4'), ('5 star', '5')], default='5', max_length=6),
        ),
    ]
