# Generated by Django 3.0.7 on 2021-06-29 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_auto_20210629_1706'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(choices=[('1 star', '1 star'), ('2 star', '2 star'), ('3 star', '3 star'), ('4 star', '4 star'), ('5 star', '5 star')], default='5 star', max_length=6)),
                ('optional_text', models.TextField(max_length=1000, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='optional_text',
        ),
        migrations.RemoveField(
            model_name='user',
            name='rating',
        ),
    ]
