# Generated by Django 3.0.7 on 2021-06-29 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_auto_20210629_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='user',
            field=models.CharField(default='anonymous user', max_length=200),
        ),
    ]
