# Generated by Django 3.0.7 on 2021-07-01 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_auto_20210629_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='client_ip',
            field=models.GenericIPAddressField(),
        ),
    ]
