# Generated by Django 3.0.7 on 2021-07-02 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_auto_20210701_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='client_ip',
            field=models.GenericIPAddressField(null=True),
        ),
    ]
