# Generated by Django 3.0.7 on 2021-06-26 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_auto_20210626_1632'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile_picture',
        ),
        migrations.AddField(
            model_name='user',
            name='file',
            field=models.ImageField(default=-1.0, upload_to='photos'),
            preserve_default=False,
        ),
    ]
