# Generated by Django 3.0.7 on 2021-07-10 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_auto_20210702_1021'),
    ]

    operations = [
        migrations.CreateModel(
            name='RatingFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(choices=[('1 star', '1 star'), ('2 star', '2 star'), ('3 star', '3 star'), ('4 star', '4 star'), ('5 star', '5 star')], default='5 star', max_length=6)),
                ('feedback_text', models.TextField(max_length=1000, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='feedback_text',
        ),
        migrations.RemoveField(
            model_name='user',
            name='rating',
        ),
    ]
