# Generated by Django 3.0.7 on 2021-06-26 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_auto_20210626_2014'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(default=-1.0, upload_to='user/profile_photo/'),
            preserve_default=False,
        ),
    ]
