# Generated by Django 3.0.7 on 2021-06-26 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_user_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='file',
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
