# Generated by Django 3.0.7 on 2021-07-10 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0013_geeksmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GeeksModel',
        ),
    ]
