# Generated by Django 3.0.7 on 2021-07-10 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0014_delete_geeksmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RatingFeedback',
        ),
        migrations.AddField(
            model_name='user',
            name='feedback_text',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='rating',
            field=models.CharField(choices=[('1 star', '1 star'), ('2 star', '2 star'), ('3 star', '3 star'), ('4 star', '4 star'), ('5 star', '5 star')], default='5 star', max_length=6),
        ),
    ]
