# Generated by Django 3.0.7 on 2021-07-10 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0016_ratingfeedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ratingfeedback',
            name='name',
        ),
    ]
