# Generated by Django 3.0.7 on 2021-07-10 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0017_remove_ratingfeedback_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratingfeedback',
            name='rating',
            field=models.CharField(choices=[('5 star', '5 star'), ('4 star', '4 star'), ('3 star', '3 star'), ('2 star', '2 star'), ('1 star', '1 star')], default='5 star', max_length=6),
        ),
        migrations.AlterField(
            model_name='user',
            name='rating',
            field=models.CharField(choices=[('5 star', '5 star'), ('4 star', '4 star'), ('3 star', '3 star'), ('2 star', '2 star'), ('1 star', '1 star')], default='5 star', max_length=6),
        ),
    ]
