# Generated by Django 3.0.7 on 2021-07-10 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0020_guestuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestuser',
            name='email',
            field=models.CharField(default='suresh@tipstat.com', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='guestuser',
            name='password',
            field=models.CharField(default='tipstattipstat', max_length=68),
        ),
    ]
