# Generated by Django 3.0.7 on 2021-07-10 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0021_auto_20210710_2302'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GuestUser',
        ),
    ]
