# Generated by Django 3.0.7 on 2021-07-12 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0023_guestuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestuser',
            name='amount',
            field=models.IntegerField(null=True),
        ),
    ]
