# Generated by Django 3.0.7 on 2021-07-19 04:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0024_auto_20210712_1141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guestuser',
            name='id',
        ),
        migrations.AddField(
            model_name='guestuser',
            name='secret_key',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AddField(
            model_name='guestuser',
            name='transaction_successful_ID',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
