# Generated by Django 3.0.7 on 2021-07-19 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0025_auto_20210719_1020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='feedback_text',
        ),
        migrations.RemoveField(
            model_name='user',
            name='rating',
        ),
    ]
