# Generated by Django 3.0.7 on 2021-07-19 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0026_auto_20210719_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='amount',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='charities',
            field=models.TextField(max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='portfolio_name',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
