# Generated by Django 3.0.7 on 2021-07-19 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0027_auto_20210719_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='no_of_transactions',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
