# Generated by Django 3.0.7 on 2021-07-19 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0030_auto_20210719_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='no_of_transactions',
            field=models.IntegerField(null=True, verbose_name='no of transactions'),
        ),
    ]
