# Generated by Django 3.0.7 on 2021-07-22 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0031_auto_20210719_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='transaction_successful_ID',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
