# Generated by Django 3.0.7 on 2021-07-22 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0032_user_transaction_successful_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestuser',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='email address'),
        ),
    ]
