# Generated by Django 3.0.7 on 2021-07-23 09:19

import authentication.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0033_auto_20210722_1140'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referrence_number', models.CharField(blank=True, default=authentication.utils.create_new_ref_number, editable=False, max_length=10, unique=True, verbose_name='referrence number')),
                ('transaction_successful_ID', models.CharField(max_length=1000, null=True)),
                ('no_of_transactions', models.IntegerField(null=True, verbose_name='no of transactions')),
                ('portfolio_name', models.CharField(max_length=1000, null=True)),
                ('amount', models.IntegerField(null=True)),
                ('charities', models.TextField(max_length=10000, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='user',
            name='charities',
        ),
        migrations.RemoveField(
            model_name='user',
            name='no_of_transactions',
        ),
        migrations.RemoveField(
            model_name='user',
            name='portfolio_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='transaction_successful_ID',
        ),
    ]
