# Generated by Django 3.0.7 on 2021-07-23 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0037_auto_20210723_1530'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertransaction',
            name='no_of_transactions',
        ),
        migrations.AddField(
            model_name='user',
            name='no_of_transactions',
            field=models.IntegerField(null=True, verbose_name='no of transactions'),
        ),
    ]
