# Generated by Django 3.0.7 on 2021-07-23 11:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0038_auto_20210723_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertransaction',
            name='user_email',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
