# Generated by Django 3.0.7 on 2021-07-23 14:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0040_remove_usertransaction_user_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usertransaction',
            options={'ordering': ['portfolio_name']},
        ),
        migrations.AddField(
            model_name='usertransaction',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
