# Generated by Django 3.0.7 on 2021-07-23 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0041_auto_20210723_2029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertransaction',
            name='user',
        ),
    ]
