# Generated by Django 3.0.7 on 2021-07-23 16:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0042_remove_usertransaction_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertransaction',
            name='user_id',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
