# Generated by Django 3.0.7 on 2021-07-23 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0043_usertransaction_user_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usertransaction',
            options={},
        ),
    ]
