# Generated by Django 3.0.7 on 2021-07-23 16:51

import authentication.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0044_auto_20210723_2207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertransaction',
            name='id',
        ),
        migrations.AlterField(
            model_name='usertransaction',
            name='referrence_number',
            field=models.CharField(blank=True, default=authentication.utils.create_new_ref_number, editable=False, max_length=10, primary_key=True, serialize=False, unique=True, verbose_name='referrence number'),
        ),
    ]
